apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ehhbu4ywc-python 
  janus-idp.io/tekton: ehhbu4ywc-python
  backstage.io/kubernetes-id: ehhbu4ywc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ehhbu4ywc-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  