apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ehhbu4ywc-python-gitops
  description: This is GitOps manifest for ehhbu4ywc-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: ehhbu4ywc-python
    janus-idp.io/tekton: ehhbu4ywc-python
    backstage.io/kubernetes-id: ehhbu4ywc-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ehhbu4ywc-python
