apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ehhbu4ywc-python
  janus-idp.io/tekton: ehhbu4ywc-python
  backstage.io/kubernetes-id: ehhbu4ywc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ehhbu4ywc-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
