apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ehhbu4ywc-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ehhbu4ywc-python 
  name: ehhbu4ywc-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ehhbu4ywc-python 
